# ==============================================================================
# AeroMesh 1-Click All-in-One Cluster Launcher
# Usage:
#   .\start.ps1                         -> Interactive Menu
#   .\start.ps1 coordinator             -> Starts Coordinator + Claymorphic Web UI
#   .\start.ps1 worker                  -> Starts Zero-Weight Worker Node
#   .\start.ps1 all                     -> Starts All-in-One Local Test Mesh (Worker+Coord+UI)
#   .\start.ps1 status                  -> Scans Tailscale cluster mesh
# ==============================================================================

[CmdletBinding()]
param (
    [Parameter(Position = 0)]
    [ValidateSet("coordinator", "worker", "all", "status", "")]
    [string]$Role = "",

    [Parameter(Mandatory = $false)]
    [string]$Model = "",

    [Parameter(Mandatory = $false)]
    [string]$Layers = "",

    [Parameter(Mandatory = $false)]
    [string]$Peers = "",

    [Parameter(Mandatory = $false)]
    [int]$Port = 0,

    [Parameter(Mandatory = $false)]
    [switch]$NoUI,

    [Parameter(Mandatory = $false)]
    [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

# 1. Ensure Compiler & Toolchain PATH, Python, and DLL directories
$binDir = Join-Path $PSScriptRoot "bin"
$userPythonDir = "C:\Users\" + $env:USERNAME + "\AppData\Local\Programs\Python"
$pyPathAdditions = ""
if (Test-Path $userPythonDir) {
    $latestPy = Get-ChildItem -Path $userPythonDir -Directory -ErrorAction SilentlyContinue | Sort-Object Name -Descending | Select-Object -First 1
    if ($latestPy) {
        $pyPathAdditions = "$($latestPy.FullName);$($latestPy.FullName)\Scripts;"
    }
}
$env:PATH = "C:\w64devkit\bin;C:\Users\" + $env:USERNAME + "\.cargo\bin;$binDir;$pyPathAdditions" + $env:PATH

# Ensure release DLLs are present
if (Test-Path "target\release") {
    try {
        Get-ChildItem -Path "bin\*.dll" -ErrorAction SilentlyContinue | Copy-Item -Destination "target\release" -Force -ErrorAction SilentlyContinue
    } catch {}
}

function Initialize-AeroMeshSecrets {
    $envPath = Join-Path $PSScriptRoot ".env"
    $apiKey = ""
    $workerSecret = ""

    if (Test-Path $envPath) {
        Get-Content $envPath | ForEach-Object {
            $line = $_.Trim()
            if (-not $line -or $line.StartsWith("#")) { return }
            $idx = $line.IndexOf("=")
            if ($idx -gt 0) {
                $k = $line.Substring(0, $idx).Trim()
                $v = $line.Substring($idx + 1).Trim().Trim('"').Trim("'")
                if ($k -eq "AEROMESH_API_KEY") { $apiKey = $v }
                if ($k -eq "AEROMESH_WORKER_SECRET") { $workerSecret = $v }
            }
        }
    }

    $createdOrUpdated = $false
    if (-not $apiKey) {
        $bytes = New-Object byte[] 32
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        $apiKey = [System.BitConverter]::ToString($bytes).Replace("-", "").ToLower()
        $createdOrUpdated = $true
    }
    if (-not $workerSecret) {
        $bytes = New-Object byte[] 32
        [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        $workerSecret = [System.BitConverter]::ToString($bytes).Replace("-", "").ToLower()
        $createdOrUpdated = $true
    }

    if ($createdOrUpdated) {
        $lines = @(
            "# AeroMesh Cluster Authentication Secrets (SEC-01 / Generated by start.ps1)",
            "# Keep this file secure and never commit it to source control.",
            "AEROMESH_API_KEY=$apiKey",
            "AEROMESH_WORKER_SECRET=$workerSecret"
        )
        if (Test-Path $envPath) {
            $existing = Get-Content $envPath -Raw
            if ($existing -notmatch "AEROMESH_API_KEY=") {
                Add-Content -Path $envPath -Value "AEROMESH_API_KEY=$apiKey"
            }
            if ($existing -notmatch "AEROMESH_WORKER_SECRET=") {
                Add-Content -Path $envPath -Value "AEROMESH_WORKER_SECRET=$workerSecret"
            }
        } else {
            Set-Content -Path $envPath -Value $lines -Encoding UTF8
        }
    }

    $env:AEROMESH_API_KEY = $apiKey
    $env:AEROMESH_WORKER_SECRET = $workerSecret
    $env:LLAMA_API_KEY = $apiKey
}

function Stop-PortConflict {
    param ([int[]]$Ports)
    foreach ($p in $Ports) {
        $conns = Get-NetTCPConnection -LocalPort $p -State Listen -ErrorAction SilentlyContinue
        if ($conns) {
            foreach ($c in $conns) {
                $pidToKill = $c.OwningProcess
                if ($pidToKill -and $pidToKill -ne $PID) {
                    Write-Host "  [*] Freeing port $p (Stopping stale process $pidToKill)..." -ForegroundColor DarkGray
                    Stop-Process -Id $pidToKill -Force -ErrorAction SilentlyContinue
                }
            }
        }
    }
}

function Test-PeerReachable {
    param ([string]$PeerStr)
    if (-not $PeerStr) { return $false }
    try {
        $parts = $PeerStr.Split(":")
        $h = $parts[0].Trim()
        $p = [int]$parts[1].Trim()
        $client = New-Object System.Net.Sockets.TcpClient
        $iar = $client.BeginConnect($h, $p, $null, $null)
        $ok = $iar.AsyncWaitHandle.WaitOne(2000, $false)
        $client.Close()
        return $ok
    } catch {
        return $false
    }
}

function Wait-ServerReady {
    param ([string]$Url, [int]$TimeoutSeconds = 45)
    Write-Host "  [*] Initializing GPU VRAM & model weights..." -ForegroundColor DarkGray
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        try {
            $resp = Invoke-WebRequest -Uri "$Url/health" -UseBasicParsing -TimeoutSec 1 -ErrorAction SilentlyContinue
            if ($resp -and $resp.StatusCode -eq 200) {
                Write-Host "  [+] Engine Ready! Model loaded in GPU memory." -ForegroundColor Green
                return $true
            }
        } catch {}
        Start-Sleep -Milliseconds 600
    }
    return $false
}

function Get-AeroMeshExe {
    if (Test-Path "target\release\aeromesh.exe") {
        return (Resolve-Path "target\release\aeromesh.exe").Path
    }
    return ""
}

function Show-AeroMeshBanner {
    Write-Host ""
    Write-Host "========================================================================" -ForegroundColor Cyan
    Write-Host "   [+] AEROMESH: DISTRIBUTED ZERO-WEIGHT LLM CLUSTER ENGINE             " -ForegroundColor Cyan
    Write-Host "   Windows + NVIDIA CUDA + Tailscale WireGuard (0.0 MB Wire Transfer)  " -ForegroundColor DarkCyan
    Write-Host "========================================================================" -ForegroundColor Cyan
}

function Find-ModelPath {
    param ([string]$ExplicitPath)
    if ($ExplicitPath -and (Test-Path $ExplicitPath)) {
        return $ExplicitPath
    }
    
    # Check for primary DeepSeek model first if present
    if (Test-Path "models\test.gguf") {
        return "models/test.gguf"
    }

    # Dynamically scan models/ or current directory for any other .gguf files
    $allGgufs = Get-ChildItem -Path @("models", ".") -Filter "*.gguf" -File -ErrorAction SilentlyContinue
    if ($allGgufs -and $allGgufs.Count -gt 0) {
        $first = $allGgufs[0]
        if ($first.Directory.Name -eq "models") {
            return ("models/" + $first.Name)
        }
        return $first.Name
    }

    return ""
}

function Get-PythonCommand {
    if (Test-Path ".\.venv\Scripts\python.exe") {
        return (Resolve-Path ".\.venv\Scripts\python.exe").Path
    }
    # Test if python in PATH actually executes (to avoid Microsoft Store dummy shim)
    try {
        $null = & python --version 2>$null
        if ($LASTEXITCODE -eq 0) {
            return "python"
        }
    } catch {}

    # Test py launcher
    try {
        $null = & py -3 --version 2>$null
        if ($LASTEXITCODE -eq 0) {
            return "py"
        }
    } catch {}

    # Check common user install paths
    $userPy = "C:\Users\" + $env:USERNAME + "\AppData\Local\Programs\Python"
    if (Test-Path $userPy) {
        $found = Get-ChildItem -Path $userPy -Filter "python.exe" -Recurse -Depth 2 -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($found) {
            return $found.FullName
        }
    }
    return ""
}

function Get-TailscaleIPv4 {
    if (Get-Command tailscale -ErrorAction SilentlyContinue) {
        try {
            $ip = (tailscale ip -4 2>$null).Trim()
            if ($ip) { return $ip }
        } catch {}
    }
    return "127.0.0.1"
}

# ------------------------------------------------------------------------------
# INTERACTIVE SELECTION (IF NO ROLE PROVIDED)
# ------------------------------------------------------------------------------
Show-AeroMeshBanner
Initialize-AeroMeshSecrets

$detectedModel = Find-ModelPath -ExplicitPath $Model
$modelName = "No .gguf found in models/"
if ($detectedModel) {
    $modelName = [System.IO.Path]::GetFileName($detectedModel)
}

$localTailscaleIP = Get-TailscaleIPv4

Write-Host ""
Write-Host "  [-] Local Tailscale IP:  " -NoNewline -ForegroundColor Gray
Write-Host "$localTailscaleIP" -ForegroundColor Green
Write-Host "  [-] Detected Model:      " -NoNewline -ForegroundColor Gray
Write-Host "$modelName" -ForegroundColor Yellow
Write-Host "  [-] Wire Weight Transfer:" -NoNewline -ForegroundColor Gray
Write-Host " 0.0 MB (P2P Activation Streaming)" -ForegroundColor Cyan
Write-Host "  [-] Control Surface Auth:" -NoNewline -ForegroundColor Gray
Write-Host " SEC-01 Active (API Key + Worker Handshake Token)" -ForegroundColor Green
Write-Host "------------------------------------------------------------------------" -ForegroundColor DarkGray

if (-not $Role) {
    Write-Host ""
    Write-Host "Select your node role for this machine:" -ForegroundColor White
    Write-Host "  [1] " -NoNewline -ForegroundColor Cyan
    Write-Host "Coordinator Node + Web UI " -NoNewline -ForegroundColor Green
    Write-Host "(Laptop A: Runs Layers 0..24, Hosts API + Web Interface)" -ForegroundColor Gray

    Write-Host "  [2] " -NoNewline -ForegroundColor Cyan
    Write-Host "Worker Node               " -NoNewline -ForegroundColor Yellow
    Write-Host "(Laptop B: Runs Layers 25..48 + LM Head on Port 50052)" -ForegroundColor Gray

    Write-Host "  [3] " -NoNewline -ForegroundColor Cyan
    Write-Host "Full Local Test Mesh      " -NoNewline -ForegroundColor Magenta
    Write-Host "(Starts Worker + Coordinator + Web UI together locally)" -ForegroundColor Gray

    Write-Host "  [4] " -NoNewline -ForegroundColor Cyan
    Write-Host "Cluster Status / Probe    " -NoNewline -ForegroundColor White
    Write-Host "(Scans Tailscale Mesh for active worker nodes)" -ForegroundColor Gray

    Write-Host "  [Q] Quit" -ForegroundColor DarkGray
    Write-Host ""

    $choice = Read-Host "Enter choice [1, 2, 3, 4, Q]"
    switch ($choice.Trim().ToUpper()) {
        "1" { $Role = "coordinator" }
        "2" { $Role = "worker" }
        "3" { $Role = "all" }
        "4" { $Role = "status" }
        default {
            Write-Host ""
            Write-Host "Exiting AeroMesh Launcher." -ForegroundColor DarkGray
            Write-Host ""
            exit 0
        }
    }
}

# ------------------------------------------------------------------------------
# ROLE EXECUTION
# ------------------------------------------------------------------------------

# 1. STATUS
if ($Role -eq "status") {
    Write-Host ""
    Write-Host "[+] Scanning Tailscale Cluster Nodes..." -ForegroundColor Cyan
    cargo run --bin aeromesh -- status
    exit 0
}

# Check Model Existence for Compute Roles
if (-not $detectedModel) {
    Write-Host ""
    Write-Host "[-] ERROR: No .gguf model found in 'models/' directory!" -ForegroundColor Red
    Write-Host "Please place a model (e.g. models/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf) and retry." -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

# 2. WORKER NODE (Laptop B)
if ($Role -eq "worker") {
    $workerPort = 50052
    if ($Port -gt 0) { $workerPort = $Port }

    $bindStr = "0.0.0.0:" + $workerPort

    # Free stale ports
    Stop-PortConflict @($workerPort)

    Write-Host ""
    Write-Host "[+] Starting AeroMesh Zero-Weight Worker Node (Laptop B)..." -ForegroundColor Cyan
    Write-Host "  Model:     $modelName" -ForegroundColor Gray
    Write-Host "  Port:      $workerPort" -ForegroundColor Gray
    Write-Host "  Binding:   $bindStr" -ForegroundColor Green
    Write-Host "  SSD Cache: ENABLED (0.0 MB weights transferred over network)" -ForegroundColor Yellow
    Write-Host ""

    $rpcServerExe = Join-Path $PSScriptRoot "bin\ggml-rpc-server.exe"
    if (Test-Path $rpcServerExe) {
        & $rpcServerExe -H 0.0.0.0 -p $workerPort -c
    } else {
        cargo run --release --bin aeromesh -- worker --port $workerPort --cache
    }
    exit 0
}

# 3. FULL LOCAL TEST MESH (Worker + Coordinator + Web UI)
if ($Role -eq "all") {
    $apiPort = 8080
    if ($Port -gt 0) { $apiPort = $Port }
    $uiPort = 7860
    $pythonExe = Get-PythonCommand

    if (-not $pythonExe) {
        Write-Host ""
        Write-Host "[-] ERROR: Python executable not found!" -ForegroundColor Red
        exit 1
    }

    $coordUrl = "http://127.0.0.1:" + $apiPort
    $uiUrl = "http://127.0.0.1:" + $uiPort

    # Free stale ports
    Stop-PortConflict @($apiPort, $uiPort, 50052)

    Write-Host ""
    Write-Host "[+] Launching Full Local Demo Mesh (Worker + Coordinator + Web UI)..." -ForegroundColor Cyan
    Write-Host "  Model:       $modelName" -ForegroundColor Gray
    Write-Host "  Coordinator: $coordUrl" -ForegroundColor Green
    Write-Host "  Worker:      127.0.0.1:50052 (Stage 2 Loopback)" -ForegroundColor Yellow
    Write-Host "  Web UI:      $uiUrl" -ForegroundColor Cyan
    Write-Host ""

    $rpcServerExe = Join-Path $PSScriptRoot "bin\ggml-rpc-server.exe"
    $serverExe = Join-Path $PSScriptRoot "bin\llama-server.exe"

    $workerProc = Start-Process -FilePath $rpcServerExe -ArgumentList @("-H", "127.0.0.1", "-p", "50052", "-c") -PassThru -NoNewWindow
    Start-Sleep -Milliseconds 1000

    $serverArgs = @("-m", "$detectedModel", "--rpc", "127.0.0.1:50052", "-ngl", "99", "--port", "$apiPort", "--host", "127.0.0.1", "-fa", "on")
    if ($env:AEROMESH_API_KEY) {
        $serverArgs += @("--api-key", "$env:AEROMESH_API_KEY")
    }
    $rustProc = Start-Process -FilePath $serverExe -ArgumentList $serverArgs -PassThru -NoNewWindow
    
    $isReady = Wait-ServerReady $coordUrl 45

    if (-not $NoBrowser -and $isReady) {
        Start-Process $uiUrl
    }

    # Run Python Web UI in foreground
    try {
        $env:AEROMESH_ENDPOINT = $coordUrl
        $env:PORT = "7860"
        if ($pythonExe -eq "python") {
            python app.py
        } else {
            & $pythonExe app.py
        }
    } finally {
        Write-Host ""
        Write-Host "Shutting down local cluster mesh..." -ForegroundColor Yellow
        if ($rustProc -and -not $rustProc.HasExited) {
            Stop-Process -Id $rustProc.Id -Force -ErrorAction SilentlyContinue
        }
        if ($workerProc -and -not $workerProc.HasExited) {
            Stop-Process -Id $workerProc.Id -Force -ErrorAction SilentlyContinue
        }
    }
    exit 0
}

# 4. COORDINATOR NODE (Laptop A)
if ($Role -eq "coordinator") {
    $apiPort = 8080
    if ($Port -gt 0) { $apiPort = $Port }

    $pythonExe = Get-PythonCommand

    # Check for Peer IP if not supplied
    if (-not $Peers) {
        Write-Host ""
        Write-Host "Enter the Worker Address (ZeroTier / LAN / Tailscale IP:Port, example: 10.78.133.107:50052):" -ForegroundColor Yellow
        $enteredPeer = Read-Host "Worker Peer IP:Port"
        if ($enteredPeer) {
            $Peers = $enteredPeer.Trim()
        }
    }

    if ($Peers -and -not $Peers.Contains(":")) {
        $Peers = "$($Peers.Trim()):50052"
    }

    $coordUrl = "http://127.0.0.1:" + $apiPort
    $uiUrl = "http://127.0.0.1:7860"

    $workerStatusStr = "Local Standalone"
    $isPeerReachable = $false
    if ($Peers) {
        $isPeerReachable = Test-PeerReachable $Peers
        if ($isPeerReachable) {
            $workerStatusStr = "$Peers (✅ ONLINE)"
        } else {
            $workerStatusStr = "$Peers (⚠️ UNREACHABLE - Check Laptop B / start.ps1 worker)"
        }
    }

    # Free stale ports before launching
    Stop-PortConflict @($apiPort, 7860)

    Write-Host ""
    Write-Host "[+] Launching AeroMesh Coordinator (Laptop A)..." -ForegroundColor Cyan
    Write-Host "  Model:       $modelName" -ForegroundColor Gray
    Write-Host "  Worker Peer: $workerStatusStr" -ForegroundColor Yellow
    Write-Host "  API Server:  $coordUrl" -ForegroundColor Green
    Write-Host "  Web UI:      $uiUrl" -ForegroundColor Cyan
    Write-Host ""

    $serverExe = Join-Path $PSScriptRoot "bin\llama-server.exe"
    $serverArgs = @("-m", "$detectedModel", "-ngl", "99", "--port", "$apiPort", "--host", "127.0.0.1", "-fa", "on")
    if ($env:AEROMESH_API_KEY) {
        $serverArgs += @("--api-key", "$env:AEROMESH_API_KEY")
    }
    if ($Peers -and $isPeerReachable) {
        $serverArgs += @("--rpc", "$Peers")
    } elseif ($Peers -and -not $isPeerReachable) {
        Write-Host "  [-] WARNING: Could not connect to $Peers." -ForegroundColor DarkYellow
        Write-Host "      Starting in high-speed local GPU mode. Run '.\start.ps1 worker' on Laptop B to enable distributed cluster." -ForegroundColor Gray
        Write-Host ""
    }

    $rustProc = Start-Process -FilePath $serverExe -ArgumentList $serverArgs -PassThru -NoNewWindow
    
    # Wait until engine is fully loaded in VRAM before launching UI
    $isReady = Wait-ServerReady $coordUrl 45

    if (-not $NoBrowser -and $isReady) {
        Start-Process $uiUrl
    }

    # Run Python Web UI in foreground
    try {
        $env:AEROMESH_ENDPOINT = $coordUrl
        $env:PORT = "7860"
        if ($pythonExe -eq "python") {
            python app.py
        } else {
            & $pythonExe app.py
        }
    } finally {
        Write-Host ""
        Write-Host "Shutting down coordinator API server..." -ForegroundColor Yellow
        if ($rustProc -and -not $rustProc.HasExited) {
            Stop-Process -Id $rustProc.Id -Force -ErrorAction SilentlyContinue
        }
    }
}
